from langgraph.graph import StateGraph,add_messages
from typing import TypedDict,Annotated,List,Optional
from langchain.tools import tool
from langchain_openai import ChatOpenAI
import pyodbc
from langchain_core.messages import HumanMessage,AIMessage,ToolMessage
from Agents.Request_Agent.prompts import request_document_system_message, system_message
from pydantic import Field,BaseModel
import requests
import os
from langgraph.types import interrupt,Command
from langgraph.graph import START,END
from langgraph.checkpoint.memory import MemorySaver

import uuid
from Agents.Request_Agent.utils.mail_sending_agent import communication_agent

checkpointer = MemorySaver()

class DocumentState(TypedDict):
    input : Annotated[list[str],add_messages]
    active_state : str
    human_interrupt : bool
    interrupt_question : str
    email_id : str
    file_extension :str
    output : str

class ToolCall(BaseModel):
    name: str = Field(
        description=(
            "The name of the tool to invoke. Must exactly match one of the registered tools. "
            "Tool calls should ONLY be generated if ALL required arguments are available. "
            "If arguments are missing or ambiguous, do not create a tool call — instead set human_interrupt=True."
        )
    )
    arguments: Optional[dict] = Field(
        default=None,
        description=(
            "The arguments for the tool as key-value pairs. "
            "Must include ALL required parameters for the chosen tool. "
            "If not available, set human_interrupt=True and do not include the tool call."
        ),
    )

class DocLlmSchema(BaseModel):
    message: Optional[List[str]] = Field(
        default=None,
        description=(
            "A list of outputs generated by the model. "
            "Each item can be either a direct textual response for the user "
            "or the name of a tool/function that should be invoked. "
            "If multiple steps are required, include them in order."
            "if tool calls are required then this field should be null." \
            "**IMPORTANT**: Tool calls can only be made when all input arguments are available "
        )
    )
    tool_call: Optional[List[ToolCall]] = Field(
        description="single or list of tool calls required to complete the given task"
    )
    human_interrupt: bool = Field(
        default=False,
        description=(
            "Set to True if the model does not have enough clarity or confidence "
            "to act on the query directly. In such cases, the model must ask the user "
            "for clarification before proceeding. False if the model is certain."
        )
    )
    interrupt_question: Optional[str] = Field(
        default=None,
        description=(
            "A natural-language follow-up question that the model should ask the user "
            "to resolve uncertainty. Only required when human_interrupt is True; "
            "otherwise this field should be None."
        )
    )


class requestobject(TypedDict):
    document_name : list[str] = Field(description="original name of the document from the available list")
    matching_percentage : int = Field(description = "An integer describing matching percentage between 1 to 100")

# Define input schema for better parameter extraction
class DocumentDownloadInput(BaseModel):
    webtop_id: str = Field(description="An alphanumeric id for which the document needs to be downloaded. Example: '464PZ8600789'")
    document_name: str = Field(description="Name of the document to be downloaded. Example: 'vm summary', 'Loan Agreement', 'Aadhar card'")

class FetchToolInput(BaseModel):
    webtop_id: str = Field(description="An alphanumeric id unique id for which document download progress will be checked. Example: '464PZ8600789'")
    document_name: str = Field(description="Document name whose progress needs to be checked for given webtop_id. Example: 'vm summary', 'Loan Agreement', 'Aadhar card'")


llm = ChatOpenAI(model = 'gpt-4o-mini',api_key ="  ",temperature =0)

# tools


def insert_task_record(work_id: str, webtop_id: str, document_name: str) -> bool:
    """
    Inserts a new task record into the Task_Test table.

    Args:
        work_id (str): Work ID of the task.
        webtop_id (str): Application/Application ID.
        document_name (str): Name of the document.

    Returns:
        bool: True if insert was successful, False otherwise.
    """

    query = """
        INSERT INTO [CustomerSupportGPT].[dbo].[Task_Test] 
        (Work_ID, Application_ID, Task_Name, Task_Status, Doc_Name)
        VALUES (?, ?, 'request', 'New', ?)
    """

    conn_str = (
        "DRIVER={ODBC Driver 17 for SQL Server};"
        "SERVER=216.48.191.98;"
        "DATABASE=CustomerSupportGPT;"
        "UID=ibsadmin;"
        "PWD=Viking@@ibs2023;"
    )

    try:
        with pyodbc.connect(conn_str, autocommit=True) as conn:
            cursor = conn.cursor()
            cursor.execute(query, (work_id, webtop_id, document_name))
            print(f"✅ Insert successful for Work_ID={work_id}, Webtop_ID={webtop_id}")
            return True
    except Exception as e:
        print(f"❌ Error inserting record: {e}")
        return False


def execute_sql_query(query : str) -> list:

    """
    Executes a SQL SELECT query on the SQL Server and returns the results as a list of dicts.
    
    Parameters:
        query (str): A SELECT query string.
    
    Returns:
        List[dict]: List of rows as dictionaries.
    """
    

    conn_str = (
        "DRIVER={ODBC Driver 17 for SQL Server};"
        "SERVER=216.48.191.98;"
        "DATABASE=Doc_Repository;"  # or Kredit_Bee_FC based on query
        "UID=ibsadmin;"
        "PWD=Viking@@ibs2023;"
    )
    try:
        with pyodbc.connect(conn_str) as conn:
            print("✅ Connection successful!")
    except Exception as e:
        print("❌ Connection failed:", e)
    try:
        with pyodbc.connect(conn_str, autocommit=True) as conn:
            cursor = conn.cursor()
            cursor.execute(query)
            columns = [column[0] for column in cursor.description]
            rows = cursor.fetchall()
            results = [dict(zip(columns, row)) for row in rows]
            print(f"✅ Query executed successfully. Rows fetched: {len(results)}")
            document_names = []
            for value in results:
                document_names.extend(value.values())
            document_names = ", ".join(document_names)
            return document_names
    except Exception as e:
        print(f"❌ Error executing query: {e}")
        return []

@tool(args_schema=FetchToolInput)
def fetch_tool(webtop_id : str , document_name : str) -> str:
    """
    check status of the document for download.

    input:
        webtop_id (str): An alphanumeric id unique id for which document download progress will be checked.
                             Example : "464PZ8600789"

        document_name (str):Original Name of the document fetched from Document_download tool whose progress needs to be checked for given webtop_id
                             Example : "vm summary", "Loan Agreement", "Aadhar card"

    
    output:
        str : status of document
    """

    query = f"select top(1)[Task_Status]  from [CustomerSupportGPT].[dbo].[Task_Test] where Application_ID = '{webtop_id}' and Doc_Name = '{document_name}'"

    print(query)



    while True:
        
        response = execute_sql_query(query)
        # print(response)
        if response == 'Completed':
            return f"Document '{document_name}' has been downloaded for Application id {webtop_id}"
        
        elif response =='Business Exception':
            return f"the requested document '{document_name}' was not found on document management system portal for Application id {webtop_id}"

        elif response == "System Exception":
            return f"there was some internal error while downloading the document '{document_name}' for Application id {webtop_id} please try again later"


@tool
def document_download(webtop_id : str, document_name : str) -> str:
    """
    download the document for given document name from DMS(Document Management System) portal.
    
    Input:
        webtop_id (str): An alphanumeric id for which the document needs to be downloaded.
                             Example : "464PZ8600789"

        document_name (str): Name of the document to be downloaded
                             Example : "vm summary", "Loan Agreement", "Aadhar card"

    Output:
        str : status code if the request for document download was hit successfully followed by the original document name which was used to start download process and if request was not completed then the reason for not download of that document.

    """
    if len(webtop_id)!=12 or not webtop_id.isalnum():
        return "Application id is not valid it should be a 12 digit alpha numeric id, ask user for a valid id"
    print(f'getting data list.... for {webtop_id} and document {document_name}')

    query_to_fetch_list = "select Doc_Name from [Doc_Repository].[dbo].[Document_List_Master] where Process_ID = 'D000'"

    data = execute_sql_query(query_to_fetch_list)

    
    print(data)

    print("fetched data list....")

    response = llm.with_structured_output(requestobject).invoke([
        HumanMessage(content=request_document_system_message.format(
            document=document_name, 
            Document_List=data
    
        ))
    ])

    print(f"model response : {response.get('document_name')} , {len(response.get('document_name'))}")

    if type(response.get('document_name')) == str:
        response["document_name"] = [response.get('document_name')]

    print(f"model response : {response.get('document_name')} , {len(response.get('document_name'))}")

    if len(response.get('document_name')) > 1:
        # result = interrupt(f"""please select which document you want to download from these matchin names for your given name :
        #                 {response.get('document_name')}""")
        
        # response['document_name'] = [result]
        print(f'multiple documents found {response.get('document_name')}')
        return f"tool was not executed because it found {response.get('document_name')} multiple document names please select one of the name and call the tool again"
    
    
    print(f"\n\n{response.get('document_name')} : {len(response.get('document_name'))}\n\n")
    
    if len(response.get('document_name')) == 1:
        
        data = {
        "Webtop_ID": webtop_id,
        "Process_Name": "CustomerVerification",
        "Work_ID": "123456",
        "Task_Name": "CheckCibil",
        "DocNames": response.get('document_name')[0],
        "DocFolderPath": r"C:\\CustomerSupportGPT\\Documents",
        "ScriptPath": r"C:\\Credit_GPT\\Process\\Supporting Files\\DMS_DOC_FETCH_API.py",
        "ErrorFilePath": r"C:\Credit_GPT\Process\Supporting Files\Error.txt",
        "Doc_Path": r"C:\\CustomerSupportGPT\\Documents",
        "sTo_mail": "abhirajsingh.rajpurohit@idolizesolutions.com",
        "Subject_line": "Document Processing Completed",
        "sMail_body": "Your document has been processed successfully."}


        print("score : ",response.get('matching_percentage'),"  document name : ",response.get('document_name'))
        if response.get('matching_percentage') > 50:
            print(os.getenv('DOCUMENT_DOWNLOAD_FLOW_URL',''))
            insert_task_record('1234', webtop_id, response.get('document_name')[0])
            # resp = requests.post("https://prod-09.centralindia.logic.azure.com:443/workflows/c2d24b472afd4bf59284a6a7af9b479b/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=5q3charGoRRbc0AWvLm_BsgyzO6LnjiO-lm6M4JLT8A", json=data, timeout=30)
            # resp = requests.post("https://defaultb27025bdc085406fb4beacc54b08a9.91.environment.api.powerplatform.com:443/powerautomate/automations/direct/workflows/acd57ba4fa9e4e1597c097fb241422e8/triggers/manual/paths/invoke?api-version=1&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=cbXmwfXDHibg244VhYgNreluzIn3gZAJVLaVq4Uc6jE", json=data, timeout=30)

            # print(f"{resp.status_code} {resp.text}")
            # return f"Document Download Process has started, use fetch tool now to extract status, status code : {resp.status_code}, document name : {response.get('document_name')[0]}" 
            return f"Document Download Process has started, use fetch tool now to extract status, status code : 202, document name : {response.get('document_name')[0]}"
            # return f"{resp.status_code} {resp.text} {response.get('document_name')[0]}"

        else :

            return "could not find any document in database that matches your provided document name"
        
    elif len(response.get('document_name')) == 0:
        return "no matching document name was found for the given document, no document download process started"
    else :  
        return "error occured while execution try again"

TOOL = [document_download, fetch_tool]
tools_by_name = {tool.name: tool for tool in TOOL}
llm_with_tools = llm.bind_tools(TOOL)




def llm_call(state : DocumentState) -> DocumentState:

    print('****STARTING  LLM : ****')

    state['active_state'] = 'llm_call'

    print('here i am')
    response = llm_with_tools.with_structured_output(DocLlmSchema, method="function_calling").invoke([HumanMessage(content =system_message.format(message =state['input'] ))])

    print('CHAT HISTORY : ',state['input'])
    print(f"\n**START** : {response}\n")
   
    id = str(uuid.uuid4())

    if response.human_interrupt is True:
        print("\n\ninvoking interrupt\n\n")
        return {'input':AIMessage(content = response.interrupt_question),'active_state' :'llm_call','human_interrupt' : True, 'interrupt_question' :response.interrupt_question}
    elif response.tool_call is not None:
        print("\n\ninvoking tool call\n\n")
        return {'human_interrupt' : False, 'input':AIMessage(
                content="Tool call issued.",
                tool_calls=[
                    {
                        "name": response.tool_call[0].name,
                        "args": response.tool_call[0].arguments or {},
                        "id": id,
                    }
                ],
            ),'active_state' :'llm_call'}
    else:
        return {'human_interrupt' : False, 'input':AIMessage(content = response.message),'active_state' :'communication'}

def human_interrupt(state : DocumentState) -> DocumentState:

    print('****STARTING INTERRUPT : ****')

    print('here i am :',state['active_state'])
    
    if state['active_state'] == 'llm_call':
        print('llm interrupt')
        input= interrupt(state['interrupt_question'])
        print('interrupt completed')
        return {'input': [HumanMessage(content = input)],'human_interrupt':False,'interrupt_question': None}
    
    else :
        print('communication interrupt')
        input= interrupt(state['interrupt_question'])
        return Command(update = {'email_id': input,'human_interrupt':False,'interrupt_question': None},
                   goto='communication')

def tool_call(state : DocumentState) -> DocumentState:

    print('****STARTING TOOL CALL : ****')

    tool_calls = state['input'][-1].tool_calls

    # Execute all tool calls
    observations = []
    for tool_call in tool_calls:
        tool = tools_by_name[tool_call["name"]]
        observations.append(tool.invoke(tool_call["args"]))
            
    # Create tool message outputs
    tool_outputs = [
        ToolMessage(
            content=observation,
            name=tool_call["name"],
            tool_call_id=tool_call["id"]
        ) for observation, tool_call in zip(observations, tool_calls)
    ]

    return {'input' : tool_outputs}



def should_continue(state: DocumentState):
    """Decide the next step in the workflow."""

    print('****STARTING CONDITIONAL FLOW : ****')

    # print("entered deciding flow")

    last_message = state["input"][-1]
    print(f"**INTERRUPT ISSUE** : ")
    if state['human_interrupt'] is True and state['interrupt_question'] is not None:
        return 'human_interrupt'

    # Case 1: LLM decided to call a tool
    if isinstance(last_message, AIMessage) and getattr(last_message, "tool_calls", None):
        print(last_message)
        # print("\n\ntools were called\n\n")
        return "tool_call"

    # Case 2: A tool just executed, return back to LLM
    elif isinstance(last_message, ToolMessage):
        # print(f'\n\nthis is the issue\n\n')
        return "llm_call"

    # Case 3: No tools needed, end the flow
    # print("\n\nflow reach end\n\n")
    else:
        print(f"****FINAL RESPONSE**** : {last_message}")
        return "communication_agent"


def communication(state: DocumentState):
    try:
        print('****STARTING COMMUNICATION AGENT : ****')
    
        state['active_state'] = 'communication'
        mail_output = ''
    
        input_message = state["input"][0]
        document_download_status = state["input"][-1]
    
        class is_mail_required(TypedDict):
            mail_required: bool = Field(default=False, description="Set to True if mail send is required, else False")
            is_mail_present : bool = Field(description="Set to True if mail is present in the message, else False")
            mail_id :str = Field(default = None,description = 'extract the mail id if present else None')
            document_name : str = Field(default=None, description="extract the name of the document present in the query")
        
        Mail_requirement_check_message = f"""
            Based on the user query below, determine if the mail sending tool should be used.
            `Mail_required` should be True only if mail sending action is explicitly mentioned in the query.
            `is_mail_present` should be True if a Valid  mail id exists ending with '@idloizesolutions.com' in the given query, else False.
            `mail_id` should contain valid mail id from query that is ending with '@idloizesolutions.com', else None.
            `document_name` will contain valid document name that is present in the user query.
            Query: {input_message.content} {document_download_status.content}
        """
    
    
        print(Mail_requirement_check_message)
    
        response = llm.with_structured_output(is_mail_required).invoke([HumanMessage(content=Mail_requirement_check_message)])
        
        if response['mail_required']:
        
            extension_fetch_query = f"select file_extension from [Doc_Repository].[dbo].[Document_List_Master]  where Process_ID = 'D000' and Doc_Name = '{response['document_name']}'"
    
            extension = execute_sql_query(extension_fetch_query)
    
            print(extension)
        
            print("Mail requirement check response:", response)
    
            if state['email_id'] is None:
            
                if response.get('is_mail_present') is False:
                
                    print('mail not found going for extraction')
                    return Command(update = {'interrupt_question' : "please provide the mail id to send the mail?"},goto='human_interrupt')
                else :
                
                    state['email_id'] = response.get('mail_id')
    
            
    
            mail_output =  communication_agent(f'mail_id = {state['email_id']} , input = {input_message} , document download status = {document_download_status}, document extension : .{extension}')
            print('communication result is : ',type(document_download_status.content[0]),type(mail_output))
            status = document_download_status.content[0] + ', '+ mail_output
            print(status)
            return Command(update = {'output':status },goto=END)
                
                # Here you can add logic to prepare and call communication_agent
        else:
                print("Mail sending is not required. Proceed without invoking communication_agent.")
                return Command(update = {'output':document_download_status.content[0] },goto=END)
            
    except:
        print("Unexpected LLM output. Handle error or fallback.")
        return Command(update = {'output':"communication agent produced Unexpected output." },goto=END)
            


graph = StateGraph(DocumentState)
graph.add_node("llm_call",llm_call)
graph.add_node("human_interrupt",human_interrupt)
graph.add_node('tool_call',tool_call)
graph.add_node('communication',communication)


graph.add_edge(START,"llm_call")
graph.add_edge("tool_call","llm_call")
graph.add_edge("human_interrupt","llm_call")
graph.add_conditional_edges("llm_call",should_continue,
                           {"tool_call":"tool_call",
                            'human_interrupt':'human_interrupt',
                            "communication_agent":'communication'})
graph.add_edge('communication',END)
compiled_request_graph = graph.compile(checkpointer=checkpointer)
